services:
  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    image: todo-frontend
    container_name: todo-frontend

  todo-backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    image: todo-backend
    container_name: todo-backend
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/the_database?authSource=admin
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: todo-mongo
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database

  redis:
    image: redis:latest
    container_name: todo-redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:1.20.1
    container_name: todo-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - todo-frontend
      - todo-backend

volumes:
  mongo_data:
  redis_data:
