services:
  app:
    image: hello-front-dev
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5173:5173
    container_name: hello-front-dev